version: '3.1'

services: 
  api-calculador:
    image: alonsozy/final-project:1.0.7
    build: ./
    restart: always
    ports:
      - 1080:8080
    networks:
      - backend
      
  test-newman:
    image: alonsozy/test-newman:1.0.7
    build: ./test-newman/
    environment:
      URL_SERVER: http://192.168.99.100:1080
    restart: always
    depends_on:
      - api-calculador
    restart: on-failure
    networks:
      - backend
    
networks:
  backend: 
    
    