version: '3.1'

services: 
  api-calculador:
    image: alonsozy/final-project:2.0.1
    build: ./
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend
      
  test-newman:
    image: alonsozy/test-newman:2.0.1
    build: ./test-newman/
    environment:
      URL_SERVER: http://192.168.99.100:8080
    restart: always
    depends_on:
      - api-calculador
    restart: on-failure
    networks:
      - backend
    
networks:
  backend: 
    
    